baseURL = "https://bartender-mu.github.io/neovim/"
languageCode = "en-us"
title = "Bartender's Neovim Configuration"
theme = "ananke"

[params]
  github_repo = "https://github.com/bartender-mu/neovim"
  description = "A customized Neovim configuration by bartender-mu, optimized for productivity and aesthetics."
  favicon = ""
  background_image = "/images/neovim-bg.jpg"
  custom_css = ["/css/custom.css"]

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2
[[menu.main]]
  name = "GitHub"
  url = "https://github.com/bartender-mu/neovim"
  weight = 3
